{
  "result": "Sorry, the test could not be cancelled.  It may have already started or been cancelled"
}